language: php
php:
  - 5.6
  - 7.0
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover=coverage.xml
  - vendor/bin/php-cs-fixer fix --dry-run

after_success:
  - bash <(curl -s https://codecov.io/bash)

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
  - $HOME/.composer/cache